export const featureLabels: Record<string, string> = {
  "editing-multitrack": "Multi-track video and audio editing",
  "editing-ai-clips": "AI-assisted clip selection and highlights",
  "editing-export": "One-click export for every platform",
  "editing-personal-ai": "Personal AI trained on your content for new ideas",
  "editing-scripts": "Script and caption generation from your footage",
  "editing-thumbnails": "Thumbnail and title suggestions based on your style",
  "scheduling-cross-platform": "Cross-platform scheduling & posting",
  "scheduling-optimal": "Optimal posting-time suggestions",
  "scheduling-republish": "Automated republishing and drip campaigns",
  "admin-contracts": "Contract and deal-memo templates",
  "admin-invoicing": "Invoicing and payment tracking",
  "admin-team": "Team roles, permissions, and approval flows",
  "admin-email-summary": "AI email summaries for long threads",
  "admin-email-tracking": "Email tracking with read receipts and follow-ups",
  "admin-inbox": "Unified inbox across deals, talent, and projects",
  "tracking-repost": "Track where your content is reposted or embedded",
  "tracking-ownership": "Immutable ownership records for every asset",
  "tracking-takedown": "Unauthorized use alerts and takedown assistance",
};
